import { createServer } from 'http';
import { parse } from 'url';
import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PORT = process.env.PORT || 3000;

// Import Firebase configuration
import '../server/firebase.config.js';

// Basic server to serve static files generated by Vite
const server = createServer((req, res) => {
  // Parse the request URL
  const parsedUrl = parse(req.url, true);
  const { pathname } = parsedUrl;

  // API routes
  if (pathname.startsWith('/api/')) {
    // Placeholder for actual API implementation
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ message: 'API endpoint' }));
    return;
  }

  // Default path is index.html
  let path = pathname === '/' ? '/index.html' : pathname;
  
  // Try to serve the file from the dist/public directory
  try {
    const filePath = join(__dirname, '../dist/public', path);
    const data = readFileSync(filePath);
    
    const extension = path.split('.').pop();
    const contentType = getContentType(extension);
    
    res.writeHead(200, { 'Content-Type': contentType });
    res.end(data);
  } catch (err) {
    // If file not found, serve index.html (for SPA routing)
    try {
      const data = readFileSync(join(__dirname, '../dist/public/index.html'));
      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.end(data);
    } catch (indexErr) {
      // If even index.html is not found, return 404
      res.writeHead(404);
      res.end('File not found');
    }
  }
});

// Helper to determine content type
function getContentType(extension) {
  const contentTypes = {
    'html': 'text/html',
    'css': 'text/css',
    'js': 'application/javascript',
    'json': 'application/json',
    'png': 'image/png',
    'jpg': 'image/jpeg',
    'jpeg': 'image/jpeg',
    'gif': 'image/gif',
    'svg': 'image/svg+xml',
    'ico': 'image/x-icon',
  };
  
  return contentTypes[extension] || 'text/plain';
}

server.listen(PORT, () => {
  console.log(`Server running at http://localhost:${PORT}/`);
});

// For Vercel serverless functions
export default async function handler(req, res) {
  // This is used by Vercel serverless function format
  res.status(200).json({ message: 'API endpoint for Vercel' });
}